### ISSUE TITLE
Batch processing workflow

### ISSUE THREAD

**Issue by juniuspan** [alexandergogl/SkimPDF#1]
Dear Alexander,

I found SkimPDF really useful in conversing annotations, I've made it working smoothly on my mac with "osx-automator". However, since I have little experience in coding, I failed to run the "batch processing" python script.

Could you please give me a brief introduction about the workflow to run "batch processing"
?
Thanks in advance.

Best,
Jun

**Comment by juniuspan** [comment]
Aha, I figured out why it didn't work for me. 

I initially tried in a way that imports skim_pdf and types in the codes to OS X CLI, which can certainly cause error. After reviewing the python code, I became aware that I only need to change some codes in skim_pdf.py and run "python skim_pdf.py" in order to tweak the tool to work normally.

Works like a charm now!
Thanks for providing this great tool.

**Comment by alexandergogl** [comment]
Hi Jun!

I am glad that you like the script. I think I will add an automator script that wraps the batch process so you can use it as a right-click context command.

Best,

Alexander

**Comment by alexandergogl** [comment]
> Hi Jun!
> 
> I am glad that you like the script. I think I will add an automator script that wraps the batch process so you can use it as a right-click context command.
> 
> Best,
> 
> Alexander

Sorry, I just noticed, that I have already included the batch processing command in the `skim_pdf_to_pdf_automator.py`and `skim_pdf_to_skim_automator.py` automator scripts. The automator script checks whether one file is selected (single conversion) or multiple files or folders are selected (batch conversion).

Wasn't the batch processing working for you in the first place when you selected a folder or multiple pdf files?

**Comment by juniuspan** [comment]
> > Hi Jun!
> > I am glad that you like the script. I think I will add an automator script that wraps the batch process so you can use it as a right-click context command.
> > Best,
> > Alexander
> 
> Sorry, I just noticed, that I have already included the batch processing command in the `skim_pdf_to_pdf_automator.py`and `skim_pdf_to_skim_automator.py` automator scripts. The automator script checks whether one file is selected (single conversion) or multiple files or folders are selected (batch conversion).
> 
> Wasn't the batch processing working for you in the first place when you selected a folder or multiple pdf files?

I tried "osx-automator" first successfully but didn't notice it can also batch process files. Since you have singled out a "Batch processing" title in the introduction, I assumed  running code is the very way to accomplish the task.
I've tried the automator scripts just now, they works very well, indeed a drudgery saver.

Your reminder of the scripts' batching processing function is another bonus to me:)
Thanks.

**Comment by alexandergogl** [comment]
You are welcome!
